/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kasir;

/**
 *
 * @author DELL
 */
public class Form_Home extends javax.swing.JFrame {

    /**
     * Creates new form Form_Home
     */
    public Form_Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnKasir = new javax.swing.JButton();
        BtnMember = new javax.swing.JButton();
        BtnDataPenjualan = new javax.swing.JButton();
        BtnDataBarang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel2.setText("SELAMAT DATANG DI TOKO PERDANA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        BtnKasir.setBackground(new java.awt.Color(0, 0, 204));
        BtnKasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnKasir.setText("Kasir");
        BtnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKasirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 120, 40));

        BtnMember.setBackground(new java.awt.Color(255, 153, 51));
        BtnMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMember.setText("Data Member");
        BtnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMemberActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, 40));

        BtnDataPenjualan.setBackground(new java.awt.Color(204, 0, 153));
        BtnDataPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDataPenjualan.setText("Data Penjualan");
        BtnDataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataPenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDataPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 120, 40));

        BtnDataBarang.setBackground(new java.awt.Color(0, 204, 0));
        BtnDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDataBarang.setText("Data Barang");
        BtnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDataBarangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 120, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 270));

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataPenjualanActionPerformed
        // TODO add your handling code here:
        new Form_Penjualan().show();
        this.dispose();                
    }//GEN-LAST:event_BtnDataPenjualanActionPerformed

    private void BtnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMemberActionPerformed
        // TODO add your handling code here:
        new Form_Member().show();
        this.dispose();
    }//GEN-LAST:event_BtnMemberActionPerformed

    private void BtnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDataBarangActionPerformed
        // TODO add your handling code here:
        new Form_Barang().show();
        this.dispose();                
    }//GEN-LAST:event_BtnDataBarangActionPerformed

    private void BtnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKasirActionPerformed
        // TODO add your handling code here:
        new Form_Kasir().show();
        this.dispose();
    }//GEN-LAST:event_BtnKasirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Form_Login().show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDataBarang;
    private javax.swing.JButton BtnDataPenjualan;
    private javax.swing.JButton BtnKasir;
    private javax.swing.JButton BtnMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
